<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Com18-1045-W10" ignored="0" tests="10" failures="4" timestamp="2020-04-06T08:40:03 ICT" time="0.413" errors="0">
  <testcase name="example1" time="0.114" classname="TestDemo">
    <failure type="java.lang.AssertionError" message="This test should be failed expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: This test should be failed expected [3] but found [2]
at TestDemo.example1(TestDemo.java:7)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- example1 -->
  <testcase name="example2" time="0.001" classname="TestDemo"/>
  <testcase name="example3" time="0.002" classname="TestDemo"/>
  <testcase name="example4" time="0.001" classname="TestDemo">
    <failure type="java.lang.AssertionError" message="This test should be failed">
      <![CDATA[java.lang.AssertionError: This test should be failed
at TestDemo.example4(TestDemo.java:22)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- example4 -->
  <testcase name="skippedByDependencyTest" time="0.0" classname="TestDemo">
    <skipped/>
  </testcase> <!-- skippedByDependencyTest -->
  <testcase name="test1" time="0.002" classname="TestDemo2">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at TestDemo2.test1(TestDemo2.java:7)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="TestDemo2"/>
  <testcase name="test3" time="0.002" classname="TestDemo2"/>
  <testcase name="test4" time="0.002" classname="TestDemo2">
    <failure type="java.lang.AssertionError" message="This test should be failed">
      <![CDATA[java.lang.AssertionError: This test should be failed
at TestDemo2.test4(TestDemo2.java:22)
at java.util.ArrayList.forEach(ArrayList.java:1249)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase name="skippedByDependencyTest" time="0.0" classname="TestDemo2">
    <skipped/>
  </testcase> <!-- skippedByDependencyTest -->
</testsuite>
